//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36366
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.part.ws.org.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(partBaseDto))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.part.ws.org.com/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int actionTypeField;
        
        private string errMsgField;
        
        private int flagField;
        
        private System.DateTime invokeTimeField;
        
        private bool invokeTimeFieldSpecified;
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int actionType {
            get {
                return this.actionTypeField;
            }
            set {
                this.actionTypeField = value;
                this.RaisePropertyChanged("actionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("errMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime invokeTime {
            get {
                return this.invokeTimeField;
            }
            set {
                this.invokeTimeField = value;
                this.RaisePropertyChanged("invokeTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool invokeTimeSpecified {
            get {
                return this.invokeTimeFieldSpecified;
            }
            set {
                this.invokeTimeFieldSpecified = value;
                this.RaisePropertyChanged("invokeTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36366")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://server.part.ws.org.com/")]
    public partial class partBaseDto : baseDto {
        
        private string isDangerField;
        
        private string isEffectiveField;
        
        private string isFlagField;
        
        private string isReturnField;
        
        private string isSaleField;
        
        private int miniPackField;
        
        private string partCodeField;
        
        private string partNameField;
        
        private float salePriceField;
        
        private string suptCodeField;
        
        private string unitField;
        
        private float unitPraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string isDanger {
            get {
                return this.isDangerField;
            }
            set {
                this.isDangerField = value;
                this.RaisePropertyChanged("isDanger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isEffective {
            get {
                return this.isEffectiveField;
            }
            set {
                this.isEffectiveField = value;
                this.RaisePropertyChanged("isEffective");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string isFlag {
            get {
                return this.isFlagField;
            }
            set {
                this.isFlagField = value;
                this.RaisePropertyChanged("isFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string isReturn {
            get {
                return this.isReturnField;
            }
            set {
                this.isReturnField = value;
                this.RaisePropertyChanged("isReturn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string isSale {
            get {
                return this.isSaleField;
            }
            set {
                this.isSaleField = value;
                this.RaisePropertyChanged("isSale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int miniPack {
            get {
                return this.miniPackField;
            }
            set {
                this.miniPackField = value;
                this.RaisePropertyChanged("miniPack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string partCode {
            get {
                return this.partCodeField;
            }
            set {
                this.partCodeField = value;
                this.RaisePropertyChanged("partCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string partName {
            get {
                return this.partNameField;
            }
            set {
                this.partNameField = value;
                this.RaisePropertyChanged("partName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public float salePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
                this.RaisePropertyChanged("salePrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string suptCode {
            get {
                return this.suptCodeField;
            }
            set {
                this.suptCodeField = value;
                this.RaisePropertyChanged("suptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public float unitPrace {
            get {
                return this.unitPraceField;
            }
            set {
                this.unitPraceField = value;
                this.RaisePropertyChanged("unitPrace");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.part.ws.org.com/", ConfigurationName="DMSAsync_PI06.PI06")]
    public interface PI06 {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receiveResponse receive(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receive request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="", ReplyAction="*")]
        System.IAsyncResult Beginreceive(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receive request, System.AsyncCallback callback, object asyncState);
        
        U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receiveResponse Endreceive(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receive", WrapperNamespace="http://server.part.ws.org.com/", IsWrapped=true)]
    public partial class receive {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.part.ws.org.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto[] arg0;
        
        public receive() {
        }
        
        public receive(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="receiveResponse", WrapperNamespace="http://server.part.ws.org.com/", IsWrapped=true)]
    public partial class receiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.part.ws.org.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto @return;
        
        public receiveResponse() {
        }
        
        public receiveResponse(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PI06Channel : U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class receiveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public receiveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PI06Client : System.ServiceModel.ClientBase<U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06>, U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06 {
        
        private BeginOperationDelegate onBeginreceiveDelegate;
        
        private EndOperationDelegate onEndreceiveDelegate;
        
        private System.Threading.SendOrPostCallback onreceiveCompletedDelegate;
        
        public PI06Client() {
        }
        
        public PI06Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PI06Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PI06Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PI06Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<receiveCompletedEventArgs> receiveCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receiveResponse U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06.receive(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receive request) {
            return base.Channel.receive(request);
        }
        
        public U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto receive(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto[] arg0) {
            U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receive inValue = new U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receive();
            inValue.arg0 = arg0;
            U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receiveResponse retVal = ((U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06)(this)).receive(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06.Beginreceive(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receive request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginreceive(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult Beginreceive(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto[] arg0, System.AsyncCallback callback, object asyncState) {
            U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receive inValue = new U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receive();
            inValue.arg0 = arg0;
            return ((U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06)(this)).Beginreceive(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receiveResponse U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06.Endreceive(System.IAsyncResult result) {
            return base.Channel.Endreceive(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto Endreceive(System.IAsyncResult result) {
            U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.receiveResponse retVal = ((U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.PI06)(this)).Endreceive(result);
            return retVal.@return;
        }
        
        private System.IAsyncResult OnBeginreceive(object[] inValues, System.AsyncCallback callback, object asyncState) {
            U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto[] arg0 = ((U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto[])(inValues[0]));
            return this.Beginreceive(arg0, callback, asyncState);
        }
        
        private object[] OnEndreceive(System.IAsyncResult result) {
            U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto retVal = this.Endreceive(result);
            return new object[] {
                    retVal};
        }
        
        private void OnreceiveCompleted(object state) {
            if ((this.receiveCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.receiveCompleted(this, new receiveCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void receiveAsync(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto[] arg0) {
            this.receiveAsync(arg0, null);
        }
        
        public void receiveAsync(U9.VOB.Cus.HBHDaYunsy.PlugInBE.Test.DMSAsync_PI06.partBaseDto[] arg0, object userState) {
            if ((this.onBeginreceiveDelegate == null)) {
                this.onBeginreceiveDelegate = new BeginOperationDelegate(this.OnBeginreceive);
            }
            if ((this.onEndreceiveDelegate == null)) {
                this.onEndreceiveDelegate = new EndOperationDelegate(this.OnEndreceive);
            }
            if ((this.onreceiveCompletedDelegate == null)) {
                this.onreceiveCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnreceiveCompleted);
            }
            base.InvokeAsync(this.onBeginreceiveDelegate, new object[] {
                        arg0}, this.onEndreceiveDelegate, this.onreceiveCompletedDelegate, userState);
        }
    }
}
