//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36366
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace U9.VOB.Cus.HBHDaYunsy.PlugInBE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.21.115:8080/hbfcdms/ws/PI06")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_PI06_PI06ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_PI06_PI06ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.21.115:8080/hbfcdms/ws/PI08")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_PI08_PI08ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_PI08_PI08ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.11.227:9081/dms/ws/SI02")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI02_SI02ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI02_SI02ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.11.227:9081/dms/ws/SI03")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI03_SI03ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI03_SI03ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.21.115:8080/hbfcdms/ws/SI04")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI04_SI04ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI04_SI04ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.11.227:9081/dms/ws/SI05")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI05_SI05ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI05_SI05ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.21.115:8080/hbfcdms/ws/SI08")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI08_SI08ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI08_SI08ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.11.227:9081/dms/ws/SI09")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI09_SI09ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI09_SI09ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.11.227:9081/dms/ws/SI11")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI11_SI11ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI11_SI11ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.3.21.115:8080/hbfcdms/ws/PI07")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_PI07_PI07ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_PI07_PI07ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://scisoft.eicp.net:9080/hbdyepc/ws/SI01")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI01_SI01ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_SI01_SI01ImplService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://scisoft.eicp.net:9080/dms/ws/PI09")]
        public string U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_PI09_PI09ImplService {
            get {
                return ((string)(this["U9_VOB_Cus_HBHDaYunsy_PlugInBE_DMS_PI09_PI09ImplService"]));
            }
        }
    }
}
